[package]
name = "paillier-zk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-ec = { git = "https://github.com/dfns-labs/generic-ec", branch = "d" }
generic-ec-core = { git = "https://github.com/dfns-labs/generic-ec", branch = "d" }
rand_core = { version = "0.6", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
libpaillier = { version = "0.5", default-features = false }
sha2 = { version = "0.10", default-features = false }

subtle = { version = "2.4", default-features = false }
zeroize = { version = "1", default-features = false }

thiserror = "1"

serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
generic-ec-curves = { git = "https://github.com/dfns-labs/generic-ec", branch = "d", features = ["secp256r1"] }
rand_dev = { version = "0.1.0", default-features = false }

[features]
default = ["rust"]
gmp = ["libpaillier/gmp"]
# openssl random generation doesn't respect the rng supplied from rust, and so shouldn't be used
#openssl = ["libpaillier/openssl"]
rust = ["libpaillier/rust"]

serde = ["dep:serde", "generic-ec/serde"]

[profile.dev.package.num-bigint]
opt-level = 3
[profile.dev.package.glass_pumpkin]
opt-level = 3
