[package]
name = "paillier-zk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-ec = { git = "ssh://git@github.com/dfns-labs/generic-ec", rev = "ed8aad5e4818542880af05276be86c27647ed069" }
generic-ec-core = { git = "ssh://git@github.com/dfns-labs/generic-ec", rev = "ed8aad5e4818542880af05276be86c27647ed069" }
rand_core = { version = "0.6", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
libpaillier = { version = "0.5", features = ["rust"], default-features = false }
sha2 = { version = "0.10", default-features = false }

subtle = { version = "2.4", default-features = false }
zeroize = { version = "1.5", default-features = false }

[dev-dependencies]
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
generic-ec-curves = { git = "ssh://git@github.com/dfns-labs/generic-ec", rev = "ed8aad5e4818542880af05276be86c27647ed069", features = ["secp256r1"] }
