disallowed-methods = [
    "libpaillier::unknown_order::BigNumber::random",
    "libpaillier::unknown_order::BigNumber::prime",
    "libpaillier::unknown_order::BigNumber::safe_prime",
    "libpaillier::DecryptionKey::random",
    "libpaillier::EncryptionKey::encrypt",
    "libpaillier::unknown_order::BigNumber::modpow",
]
