name: Rust

on:
  push:
    branches: [ "m" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.GENERIC_EC_KEY }}
          ${{ secrets.FAST_PAILLIER_KEY }}
    - name: Build with serde support
      run: cargo build --release --features serde
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --lib
    - name: Run doc tests
      run: echo "doc tests are TBD" && exit 1
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all --lib -- --no-deps -D clippy::all -D clippy::unwrap_used -D clippy::expect_used
    - name: Run clippy tests
      run: cargo clippy --tests -- -D clippy::all
